/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tiktok' | '/youtube' | '/api/public/hooks/scan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tiktok' | '/youtube' | '/api/public/hooks/scan'
  id: '__root__' | '/' | '/tiktok' | '/youtube' | '/api/public/hooks/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TiktokRoute: typeof TiktokRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TiktokRoute: TiktokRoute,
  YoutubeRoute: YoutubeRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
